# LiteLLM Configuration File
model_list:
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  # ... otras configuraciones
  set_verbose: true

# Configuración del límite de peticiones
rate_limiting_settings:
  # Limitar a 59 peticiones por minuto para el modelo gemini-pro
  - model: gemini-pro
    requests_per_minute: 59
    

# Server Settings
server_settings:
  # The port to run the LiteLLM proxy server on
  port: 4000
  # The host to bind the server to
  host: "0.0.0.0"
